### ISSUE TITLE
Modify apache headers to prevent DNT issue

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#104]
On Safari (~9+, desktop) having "Do Not Track" activated in Preferences causes requests to the server to be blocked -- a sort of more-nuanced version of blocking XHR requests.

Probably need something like this on our Apache config:

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
```

**Comment by BobTorgerson** [comment]
Done. This should work with the Do Not Track activated now.

**Comment by brucecrevensten** [comment]
<img width="1271" alt="screen shot 2016-07-22 at 1 10 57 pm" src="https://cloud.githubusercontent.com/assets/525049/17069874/d559ad9c-500d-11e6-88ce-6d9af7ec056f.png">

I think I may have mischaracterized this, because I still see this in Safari (9.1.1) when I have "Do Not Track" checked in preferences.  Are we serving GeoNode via Apache?

**Comment by BobTorgerson** [comment]
We needed to add the "DNT" and "Cache-Control" header lines to the CORS Allowed Headers for this to work properly while DNT was enabled. This was changed in both /home/geonode/geonode/geonode/settings.py and /etc/apache2/sites-available/001-default.conf. A restart of Apache is required after making this change for it to work.
